// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoytcnlynuicgtkzomky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhveXRjbmx5bnVpY2d0a3pvbWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzIwMzAsImV4cCI6MjA3MTQ0ODAzMH0.fgJLL3Jdv76ED0NZ0BVFmHSt-C78fhru1VlAFR6Bhcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});